# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camsys.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 9, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camPanel = QtWidgets.QWidget(self.centralwidget)
        self.camPanel.setMinimumSize(QtCore.QSize(560, 0))
        self.camPanel.setMaximumSize(QtCore.QSize(720, 16777215))
        self.camPanel.setObjectName("camPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.camPanel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cviCamera = CVImageWidget(self.camPanel)
        self.cviCamera.setMaximumSize(QtCore.QSize(560, 315))
        self.cviCamera.setObjectName("cviCamera")
        self.verticalLayout.addWidget(self.cviCamera)
        self.cviPhoto = CVImageWidget(self.camPanel)
        self.cviPhoto.setMaximumSize(QtCore.QSize(560, 315))
        self.cviPhoto.setObjectName("cviPhoto")
        self.verticalLayout.addWidget(self.cviPhoto)
        self.horizontalLayout.addWidget(self.camPanel)
        self.controlPanel = QtWidgets.QWidget(self.centralwidget)
        self.controlPanel.setObjectName("controlPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.controlPanel)
        self.verticalLayout_2.setContentsMargins(25, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.controlPanel)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wCameraSetting = QtWidgets.QWidget(self.widget)
        self.wCameraSetting.setObjectName("wCameraSetting")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wCameraSetting)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.wCameraSetting)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lCameraSettings = QtWidgets.QLabel(self.widget_3)
        self.lCameraSettings.setObjectName("lCameraSettings")
        self.horizontalLayout_8.addWidget(self.lCameraSettings)
        self.pbClickToApply = QtWidgets.QPushButton(self.widget_3)
        self.pbClickToApply.setObjectName("pbClickToApply")
        self.horizontalLayout_8.addWidget(self.pbClickToApply)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.wFocus = QtWidgets.QWidget(self.wCameraSetting)
        self.wFocus.setObjectName("wFocus")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wFocus)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lFocus = QtWidgets.QLabel(self.wFocus)
        self.lFocus.setObjectName("lFocus")
        self.horizontalLayout_2.addWidget(self.lFocus)
        self.leFocus = QtWidgets.QLineEdit(self.wFocus)
        self.leFocus.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leFocus.setObjectName("leFocus")
        self.horizontalLayout_2.addWidget(self.leFocus)
        self.verticalLayout_4.addWidget(self.wFocus)
        self.wBrightness = QtWidgets.QWidget(self.wCameraSetting)
        self.wBrightness.setObjectName("wBrightness")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wBrightness)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lBrightness = QtWidgets.QLabel(self.wBrightness)
        self.lBrightness.setObjectName("lBrightness")
        self.horizontalLayout_3.addWidget(self.lBrightness)
        self.leBrightness = QtWidgets.QLineEdit(self.wBrightness)
        self.leBrightness.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leBrightness.setObjectName("leBrightness")
        self.horizontalLayout_3.addWidget(self.leBrightness)
        self.verticalLayout_4.addWidget(self.wBrightness)
        self.wHue = QtWidgets.QWidget(self.wCameraSetting)
        self.wHue.setObjectName("wHue")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wHue)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lHue = QtWidgets.QLabel(self.wHue)
        self.lHue.setObjectName("lHue")
        self.horizontalLayout_4.addWidget(self.lHue)
        self.leHue = QtWidgets.QLineEdit(self.wHue)
        self.leHue.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leHue.setObjectName("leHue")
        self.horizontalLayout_4.addWidget(self.leHue)
        self.verticalLayout_4.addWidget(self.wHue)
        self.wContrast = QtWidgets.QWidget(self.wCameraSetting)
        self.wContrast.setObjectName("wContrast")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wContrast)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lContrast = QtWidgets.QLabel(self.wContrast)
        self.lContrast.setObjectName("lContrast")
        self.horizontalLayout_5.addWidget(self.lContrast)
        self.leContrast = QtWidgets.QLineEdit(self.wContrast)
        self.leContrast.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leContrast.setObjectName("leContrast")
        self.horizontalLayout_5.addWidget(self.leContrast)
        self.verticalLayout_4.addWidget(self.wContrast)
        self.widget_2 = QtWidgets.QWidget(self.wCameraSetting)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lExposure = QtWidgets.QLabel(self.widget_2)
        self.lExposure.setObjectName("lExposure")
        self.horizontalLayout_7.addWidget(self.lExposure)
        self.leExposure = QtWidgets.QLineEdit(self.widget_2)
        self.leExposure.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leExposure.setObjectName("leExposure")
        self.horizontalLayout_7.addWidget(self.leExposure)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.wGain = QtWidgets.QWidget(self.wCameraSetting)
        self.wGain.setObjectName("wGain")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wGain)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lGain = QtWidgets.QLabel(self.wGain)
        self.lGain.setObjectName("lGain")
        self.horizontalLayout_6.addWidget(self.lGain)
        self.leGain = QtWidgets.QLineEdit(self.wGain)
        self.leGain.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leGain.setObjectName("leGain")
        self.horizontalLayout_6.addWidget(self.leGain)
        self.verticalLayout_4.addWidget(self.wGain)
        self.verticalLayout_3.addWidget(self.wCameraSetting)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.pbBrowse = QtWidgets.QPushButton(self.widget_7)
        self.pbBrowse.setObjectName("pbBrowse")
        self.horizontalLayout_9.addWidget(self.pbBrowse)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.leBrowse = QtWidgets.QLineEdit(self.widget_8)
        self.leBrowse.setObjectName("leBrowse")
        self.verticalLayout_7.addWidget(self.leBrowse)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lSavingInterval = QtWidgets.QLabel(self.widget_10)
        self.lSavingInterval.setObjectName("lSavingInterval")
        self.horizontalLayout_11.addWidget(self.lSavingInterval)
        self.leSavingInterval = QtWidgets.QLineEdit(self.widget_10)
        self.leSavingInterval.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leSavingInterval.setObjectName("leSavingInterval")
        self.horizontalLayout_11.addWidget(self.leSavingInterval)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lTimeUntil = QtWidgets.QLabel(self.widget_9)
        self.lTimeUntil.setObjectName("lTimeUntil")
        self.horizontalLayout_10.addWidget(self.lTimeUntil)
        self.verticalLayout_8.addWidget(self.widget_9)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget)
        self.pbLight = QtWidgets.QPushButton(self.controlPanel)
        self.pbLight.setObjectName("pbLight")
        self.verticalLayout_2.addWidget(self.pbLight)
        self.pbSaveDefault = QtWidgets.QPushButton(self.controlPanel)
        self.pbSaveDefault.setObjectName("pbSaveDefault")
        self.verticalLayout_2.addWidget(self.pbSaveDefault)
        self.pbExit = QtWidgets.QPushButton(self.controlPanel)
        self.pbExit.setObjectName("pbExit")
        self.verticalLayout_2.addWidget(self.pbExit)
        self.horizontalLayout.addWidget(self.controlPanel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUnavailable = QtWidgets.QAction(MainWindow)
        self.actionUnavailable.setObjectName("actionUnavailable")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUnavailable)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lCameraSettings.setText(_translate("MainWindow", "Camera Settings"))
        self.pbClickToApply.setText(_translate("MainWindow", "Click to apply"))
        self.lFocus.setText(_translate("MainWindow", "Focus"))
        self.lBrightness.setText(_translate("MainWindow", "Brightness"))
        self.lHue.setText(_translate("MainWindow", "Hue"))
        self.lContrast.setText(_translate("MainWindow", "Contrast"))
        self.lExposure.setText(_translate("MainWindow", "Exposure"))
        self.lGain.setText(_translate("MainWindow", "Gain"))
        self.label_3.setText(_translate("MainWindow", "Save Picture to ..."))
        self.pbBrowse.setText(_translate("MainWindow", "Browse"))
        self.lSavingInterval.setText(_translate("MainWindow", "Saving Interval :"))
        self.lTimeUntil.setText(_translate("MainWindow", "Time until next picture :"))
        self.pbLight.setText(_translate("MainWindow", "Turn on light"))
        self.pbSaveDefault.setText(_translate("MainWindow", "Savec current settings as default"))
        self.pbExit.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUnavailable.setText(_translate("MainWindow", "Unavailable"))

from CVImageWidget import CVImageWidget
